<Project>
	<ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="4.0.103.3" />
    <PackageReference Include="AWSSDK.SimpleNotificationService" Version="4.0.100.15" />
    <PackageReference Include="AWSSDK.SQS" Version="4.0.100.14" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.29.2" />
	</ItemGroup>
</Project>