import TemplateSelector, { AdminTemplate } from "Admin/Template/Selector";
import { useState } from "react";
import Alert from "UI/Alert";
import Button from "UI/Button";
import Column from "UI/Column";
import Container from "UI/Container";
import Form from "UI/Form";
import Input from "UI/Input";
import Row from "UI/Row";
import {EmailTemplate} from "Api/EmailTemplate";
import TemplateApi from "Api/EmailTemplate";


const CreateEmail: React.FC = (): React.ReactElement => {

	const [error, setError] = useState<string>();
	const [selectedTemplate, setSelectedTemplate] = useState<AdminTemplate | undefined>();
	const [autoGeneratedKey, setAutoGeneratedKey] = useState<string>();

	return (
		<>
			<Container>
				<Row className='page-create'>
					<Column size={"6"}>

						<h3>{`Create new email template`}</h3>

						<Form
							action={TemplateApi.create}
							onSuccess={(res: EmailTemplate) => {
								// redirect to the page created.
								window.location.href = `/en-admin/emailtemplate/${res.id}`
							}}
							onValues={(values: EmailTemplate): EmailTemplate => {

								// set the template to the values if there is one.
								let pageBody : any = {};

								if (selectedTemplate) {
									if (selectedTemplate.template) {
										// It's a db template and requires Admin/Template to be loaded.
										pageBody = {
											t: "Admin/Template",
											data: {
												// *not* selectedTemplate.key
												templateKey: selectedTemplate.template.key
											}
										};
									} else if (selectedTemplate.componentName) {
										// It's a code one and is used in the page canvas like any other component:
										pageBody = {
											t: selectedTemplate.componentName
										};
									}
								}

								values.bodyJson = JSON.stringify(pageBody);

								return values;
							}}
							onFailed={(error) => {
								setError(error.message)
							}}
						>
							{error && <Alert variant="danger">{error}</Alert>}
							<Input
								type={'text'}
								name={'title'}
								label={`Email Template Title`}
								onInput={(ev) => {
									const value = (ev.target as HTMLInputElement).value;

									setAutoGeneratedKey(
										value
											.trim()
											.toLowerCase()
											.replace(/[^a-z0-9]+/g, '-') // Replace any non-alphanumeric sequence with '-'
											.replace(/^-+|-+$/g, '') // Remove leading/trailing dashes
									);
								}}

							/>
							<Input
								type={'text'}
								name={'key'}
								label={`Key`}
								defaultValue={autoGeneratedKey}
							/>
							<Input
								type={'text'}
								name={'subject'}
								label={`Subject`}
							/>
							<Input
								type={'text'}
								name={'sendFrom'}
								label={`Send from`}
							/>
							<Input
								type={'textarea'}
								name={'notes'}
								label={`Notes`}
							/>
							<TemplateSelector name='pageTemplate' templateType={2 as int} label={`Email Template`} onChange={setSelectedTemplate} />
							<Button type='submit'>{`Create template`}</Button>
						</Form>
					</Column>
				</Row>
			</Container>
		</>
	)
}



export default CreateEmail;